apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-executor
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: voice-executor
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
            limits:
              cpu: "8"
              memory: 16Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-executor-config
data:
  SETTINGS_FILE: "super_services.settings.prod"
  AGENT_NAME: "unpod-prod-general-agent-v3"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voice-executor
spec:
  minReplicas: 2
  maxReplicas: 10
