[tool.uv.workspace]
members = ["super", "super_services"]

[tool.uv]
dev-dependencies = [
    "pytest>=7.2.2",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
    "anyio",
    "ruff",
    "modal>=1.3.4",
]
