apiVersion: v1
kind: Secret
metadata:
  name: prefect-secrets
type: Opaque
stringData:
  PREFECT_API_DATABASE_CONNECTION_URL: ""
  PREFECT_REDIS_URL: ""
  DOCKER_REGISTRY_URL: ""
  DOCKER_REGISTRY_USER: ""
  DOCKER_REGISTRY_PASSWORD: ""
