apiVersion: v1
kind: Service
metadata:
  name: voice-executor
spec:
  type: ClusterIP
  selector:
    app: voice-executor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
